export const questions = [
  {
    unit: 9,
    english: "(to) run out of",
    german: "ausgehen, knapp werden",
    example: "there will be none available",
  },
  {
    unit: 9,
    english: "(to) collide with",
    german: "kollidieren mit",
    example: "when two events or trends meet each other with a negative result",
  },
  {
    unit: 9,
    english: "real estate broker",
    german: "Immobilienmakler",
    example: "professional intermediary for real estate transactions",
  },
  {
    unit: 9,
    english: "refurbished",
    german: "saniert, renoviert",
    example: "older offices that have been updated",
  },
  {
    unit: 9,
    english: "black hole",
    german: "Schwarzes Loch, absoluter Mangel",
    example: "nothing is available; everything has disappeared",
  },
  {
    unit: 9,
    english: "homing in on",
    german: "sich konzentrieren auf, anpeilen",
    example: "have several offices as targets to rent",
  },
  {
    unit: 9,
    english: "tired",
    german: "abgenutzt, veraltet",
    example: "in need of some updating",
  },
  {
    unit: 9,
    english: "amenities",
    german: "Annehmlichkeiten, Einrichtungen",
    example: "extra facilities such as a café, gym, health clinic",
  },
  {
    unit: 9,
    english: "(to) expire",
    german: "ablaufen, ungültig werden",
    example: "will come to an end",
  },
  {
    unit: 9,
    english: "accelerating",
    german: "beschleunigend, zunehmend",
    example: "increasing fast",
  },

  // Unit 10: B1+ - AI & Creative Industries
  {
    unit: 10,
    english: "infrastructure",
    german: "Infrastruktur",
    example: "A system that supports and allows an activity",
  },
  {
    unit: 10,
    english: "reluctant",
    german: "widerwillig, zögerlich",
    example: "If you don't really want to do something",
  },
  {
    unit: 10,
    english: "(to) rip off",
    german: "abzocken, stehlen",
    example: "If someone steals something",
  },
  {
    unit: 10,
    english: "attribution",
    german: "Zuschreibung, Quellenangabe",
    example:
      "the naming of the artist who is the source of particular material",
  },
  {
    unit: 10,
    english: "entity",
    german: "Einheit, Organisation",
    example: "An organisation or body",
  },
  {
    unit: 10,
    english: "(to) win over",
    german: "überzeugen, für sich gewinnen",
    example: "If you persuade someone to agree with you",
  },
  {
    unit: 10,
    english: "(to) draw up",
    german: "ausarbeiten, aufsetzen",
    example: "To design a policy, plan etc.",
  },
  {
    unit: 10,
    english: "(to) opt out",
    german: "sich abmelden, aussteigen",
    example: "If you say that you do not want to participate in something",
  },
  {
    unit: 10,
    english: "threat / (to) threaten",
    german: "Bedrohung / bedrohen",
    example: "a warning of negative action",
  },
  {
    unit: 10,
    english: "(to) strike a deal",
    german: "eine Vereinbarung treffen, handelseinig werden",
    example: "Another way of saying 'to do a deal'",
  },
  {
    unit: 10,
    english: "(to) permit",
    german: "erlauben, gestatten",
    example: "to allow an activity",
  },
  {
    unit: 10,
    english: "(to) warn",
    german: "warnen",
    example: "to give notice of danger",
  },
  {
    unit: 10,
    english: "flood",
    german: "überfluten, hereinströmen",
    example:
      "to arrive in overwhelming amounts (e.g. capital flooding into AI)",
  },
  {
    unit: 10,
    english: "(to) value",
    german: "bewerten, schätzen",
    example: "to estimate the monetary worth of something",
  },
  {
    unit: 10,
    english: "(to) fund",
    german: "finanzieren",
    example: "to provide money for",
  },
  {
    unit: 10,
    english: "(to) generate",
    german: "generieren, erzeugen",
    example: "to produce something (e.g. AI-generated content)",
  },
  {
    unit: 10,
    english: "(to) copyright",
    german: "urheberrechtlich schützen",
    example: "to secure legal rights to a creative work",
  },
  {
    unit: 10,
    english: "(to) train",
    german: "trainieren (Modelle)",
    example: "to teach a machine learning model using data",
  },
  {
    unit: 10,
    english: "campaign",
    german: "sich einsetzen für, Kampagne führen",
    example: "to work in an organized way toward a goal",
  },

  // Unit 11: B1+ - BYOD (Bring Your Own Device)
  {
    unit: 11,
    english: "cyber",
    german: "Cyber-, computerbezogen",
    example: "related to computers and the internet",
  },
  {
    unit: 11,
    english: "boundaries",
    german: "Grenzen",
    example: "clear ideas about what you will and will not do",
  },
  {
    unit: 11,
    english: "risk",
    german: "Risiko",
    example: "possibility of something bad happening",
  },
  {
    unit: 11,
    english: "wellbeing",
    german: "Wohlbefinden",
    example: "health of mind and body",
  },
  {
    unit: 11,
    english: "(to) access",
    german: "zugreifen auf, Zugang",
    example: "get to, look at",
  },
  {
    unit: 11,
    english: "corporate-issued",
    german: "vom Unternehmen gestellt",
    example: "provided by a company",
  },
  {
    unit: 11,
    english: "policy",
    german: "Richtlinie, Strategie",
    example: "rule, way of doing things",
  },
  {
    unit: 11,
    english: "compliance",
    german: "Einhaltung von Richtlinien",
    example: "the action of doing what the rules say",
  },
  {
    unit: 11,
    english: "out of hours",
    german: "außerhalb der Arbeitszeiten",
    example: "not during usual working time",
  },
  {
    unit: 11,
    english: "channels",
    german: "Kanäle, Kommunikationswege",
    example:
      "ways of sending messages and communicating that are approved by a company",
  },
  {
    unit: 11,
    english: "regulators",
    german: "Regulierungsbehörden",
    example:
      "government organizations that tell businesses what they can and cannot do",
  },
  {
    unit: 11,
    english: "screenshot",
    german: "Bildschirmfoto",
    example: "a photo of something shown on a computer or smartphone",
  },
  {
    unit: 11,
    english: "sacrifice",
    german: "Opfer, Verzicht",
    example: "not too bad (in context: giving something up)",
  },
  {
    unit: 11,
    english: "enthusiastic",
    german: "begeistert",
    example: "very happy or excited about something",
  },
  {
    unit: 11,
    english: "public sector",
    german: "öffentlicher Dienst",
    example: "government and state-run organizations",
  },
  {
    unit: 11,
    english: "high-profile",
    german: "prominent, hochkarätig",
    example: "important or famous",
  },
  {
    unit: 11,
    english: "in breach of",
    german: "unter Verletzung von, verstoßend gegen",
    example: "breaking (the rules or laws)",
  },
  {
    unit: 11,
    english: "falling foul of",
    german: "in Konflikt geraten mit",
    example: "getting in trouble with (e.g. regulators)",
  },
  {
    unit: 11,
    english: "whacked",
    german: "hart getroffen (mit Strafen)",
    example: "hit (with heavy fines)",
  },
  {
    unit: 11,
    english: "tread",
    german: "treten, sich bewegen",
    example: "walk, go (in context: to tread carefully)",
  },
  {
    unit: 11,
    english: "blunt",
    german: "direkt, unverblümt",
    example: "very direct",
  },

  // Unit 12: B2 - Business Ethics
  {
    unit: 12,
    english: "ethics",
    german: "Ethik, Moral",
    example: "ideas of good behaviour",
  },
  {
    unit: 12,
    english: "(to) violate",
    german: "verletzen, verstoßen gegen",
    example: "break, go against, don't obey",
  },
  {
    unit: 12,
    english: "regulator",
    german: "Regulierungsbehörde",
    example: "a person or office that supervises an industry",
  },
  {
    unit: 12,
    english: "integrity",
    german: "Integrität, Rechtschaffenheit",
    example: "the quality of being honest and good",
  },
  {
    unit: 12,
    english: "dismissal",
    german: "Entlassung",
    example: "the act removing someone from their job",
  },
  {
    unit: 12,
    english: "(to) terminate",
    german: "kündigen, beenden",
    example: "fire",
  },
  {
    unit: 12,
    english: "lapse",
    german: "Aussetzer, Verfehlung",
    example: "a temporary failure of judgment",
  },
  {
    unit: 12,
    english: "disciplinary",
    german: "disziplinarisch",
    example: "relating to punishment",
  },
  {
    unit: 12,
    english: "sparking",
    german: "auslösend, entfachend",
    example: "start, light like a fire",
  },
  {
    unit: 12,
    english: "breach",
    german: "Verstoß, Bruch",
    example: "failure, breaking the rules",
  },
  {
    unit: 12,
    english: "core",
    german: "Kern-, zentral",
    example: "very important to (e.g. core values)",
  },
  {
    unit: 12,
    english: "withheld",
    german: "zurückgehalten, verschwiegen",
    example: "didn't reveal",
  },
  {
    unit: 12,
    english: "simultaneously",
    german: "gleichzeitig",
    example: "at one time",
  },
  {
    unit: 12,
    english: "breeds",
    german: "züchtet, fördert",
    example: "creates (e.g. breeds a culture of multitasking)",
  },
  {
    unit: 12,
    english: "disproportionately",
    german: "unverhältnismäßig",
    example: "unfairly",
  },
  {
    unit: 12,
    english: "promo",
    german: "Beförderung (Slang)",
    example: "promotion - move to a better job",
  },

  // Unit 13: B2 - Tourism Taxes
  {
    unit: 13,
    english: "(to) impose",
    german: "auferlegen, verhängen",
    example:
      "to officially introduce or enforce something, often a rule or tax",
  },
  {
    unit: 13,
    english: "levy",
    german: "Abgabe, Steuer",
    example: "an official charge or tax",
  },
  {
    unit: 13,
    english: "(to) cement",
    german: "festigen, untermauern",
    example: "to firmly establish or strengthen something so it lasts",
  },
  {
    unit: 13,
    english: "(to) push back",
    german: "sich widersetzen, ablehnen",
    example: "to oppose or resist a proposal or decision",
  },
  {
    unit: 13,
    english: "(to) diminish",
    german: "verringern, schmälern",
    example: "to reduce in size, importance, or attractiveness",
  },
  {
    unit: 13,
    english: "sluggish",
    german: "schwerfällig, träge",
    example: "slow, weak, or lacking energy or progress",
  },
  {
    unit: 13,
    english: "(to) backfire",
    german: "nach hinten losgehen",
    example: "to have the opposite effect from what was intended",
  },
  {
    unit: 13,
    english: "(to) harness",
    german: "nutzbar machen, einspannen",
    example: "to make use of something effectively for a particular purpose",
  },
  {
    unit: 13,
    english: "(to) drive (growth)",
    german: "vorantreiben (Wachstum)",
    example: "to cause or stimulate growth or improvement",
  },
  {
    unit: 13,
    english: "(to) implement",
    german: "umsetzen, einführen",
    example: "to put a plan or decision into action",
  },
  {
    unit: 13,
    english: "(to) push ahead",
    german: "vorantreiben, weitermachen",
    example:
      "to continue or proceed with a plan despite difficulties or opposition",
  },
  {
    unit: 13,
    english: "hard-pressed",
    german: "unter Druck, in Schwierigkeiten",
    example: "experiencing financial difficulty or under pressure",
  },
   {
    unit: 14,
    english: "servicing",
    german: "betreiben, warten",
    example: "Operating or providing train services",
  },
  {
    unit: 14,
    english: "boosted",
    german: "angekurbelt, gesteigert",
    example: "Increased or improved significantly",
  },
  {
    unit: 14,
    english: "cumbersome",
    german: "schwerfällig, umständlich",
    example: "Complicated, heavy, or difficult to manage or use",
  },
  {
    unit: 14,
    english: "willingness",
    german: "Bereitschaft",
    example: "The readiness or openness to do something",
  },
  {
    unit: 14,
    english: "unveiled",
    german: "enthüllt, präsentiert",
    example: "Announced or revealed something officially or publicly",
  },
  {
    unit: 14,
    english: "indeterminate",
    german: "unbestimmt, vage",
    example: "Not fixed or decided; vague or uncertain",
  },
  {
    unit: 14,
    english: "to meet (rising demand)",
    german: "einen (steigenden) Bedarf decken",
    example: "To respond to or satisfy an increasing need",
  },
  {
    unit: 14,
    english: "to install",
    german: "installieren, einrichten",
    example: "To put in place and set up equipment or systems for use",
  },
  {
    unit: 14,
    english: "hubs",
    german: "Knotenpunkte, Zentren",
    example: "Central or important places where activity is concentrated",
  },
  {
    unit: 14,
    english: "infrastructure",
    german: "Infrastruktur",
    example: "The physical and organisational structures needed for the operation of a service",
  },

  // --- Unit 15 ---
  {
    unit: 15,
    english: "regimented",
    german: "streng geregelt, reglementiert",
    example: "very controlled and strict",
  },
  {
    unit: 15,
    english: "retention",
    german: "Mitarbeiterbindung, Beibehaltung",
    example: "the act of keeping something",
  },
  {
    unit: 15,
    english: "compelled",
    german: "gezwungen",
    example: "made, forced",
  },
  {
    unit: 15,
    english: "outlier",
    german: "Ausreißer, Sonderfall",
    example: "an unusual case",
  },
  {
    unit: 15,
    english: "tenacious",
    german: "beharrlich, hartnäckig",
    example: "strong and unchanging",
  },
  {
    unit: 15,
    english: "condensing",
    german: "komprimieren, verdichten",
    example: "squeezing into a smaller number of days",
  },
  {
    unit: 15,
    english: "startup",
    german: "Start-up, Neugründung",
    example: "a new small company in the IT or computer business",
  },
  {
    unit: 15,
    english: "output",
    german: "Leistung, Produktion",
    example: "work produced",
  },
  {
    unit: 15,
    english: "corporate",
    german: "unternehmerisch, Firmen-",
    example: "related to big business",
  },
  {
    unit: 15,
    english: "responsive",
    german: "reaktionsschnell, ansprechbar",
    example: "about to react quickly",
  },
  {
    unit: 15,
    english: "discipline",
    german: "Disziplin",
    example: "careful control",
  },
  {
    unit: 15,
    english: "delegates",
    german: "delegiert, überträgt",
    example: "gives specific work to people to complete",
  },
  {
    unit: 15,
    english: "industrialised",
    german: "industrialisiert",
    example: "like factory work",
  },
  {
    unit: 15,
    english: "full-fat",
    german: "vollumfänglich, extrem (im übertragenen Sinn)",
    example: "extreme, complete",
  },
  {
    unit: 15,
    english: "persisted",
    german: "bestand fort, dauerte an",
    example: "continued",
  },

  // --- Unit 16 ---
  {
    unit: 16,
    english: "compounding",
    german: "verschärfend, verschlimmernd",
    example: "making them worse",
  },
  {
    unit: 16,
    english: "snap",
    german: "unangekündigt, spontan",
    example: "unexpected and unannounced visits",
  },
  {
    unit: 16,
    english: "strained",
    german: "angespannt, belastet",
    example: "under pressure",
  },
  {
    unit: 16,
    english: "backlash",
    german: "Gegenreaktion, rechtliches Nachspiel",
    example: "dealing with possible legal complaints",
  },
  {
    unit: 16,
    english: "fostering",
    german: "fördernd, pflegend",
    example: "developing",
  },
  {
    unit: 16,
    english: "slacking",
    german: "faulenzen, sich drücken",
    example: "not working hard enough",
  },
  {
    unit: 16,
    english: "utmost",
    german: "äußerste, höchste",
    example: "the greatest",
  },
  {
    unit: 16,
    english: "to take into account",
    german: "berücksichtigen",
    example: "consider, keep in mind",
  },
  {
    unit: 16,
    english: "to set out",
    german: "darlegen, aufstellen (z.B. Erwartungen)",
    example: "define clearly",
  },
  {
    unit: 16,
    english: "to step in",
    german: "eingreifen, einschreiten",
    example: "intervene",
  },
  {
    unit: 16,
    english: "to hit out at",
    german: "scharf kritisieren, attackieren",
    example: "at people and blaming them",
  },
  {
    unit: 16,
    english: "to call in (sick)",
    german: "sich (krank)melden",
    example: "sick at the beginning of the day",
  },
  {
    unit: 16,
    english: "to rely on",
    german: "sich verlassen auf, bauen auf",
    example: "high pay to attract and retain staff",
  },
  {
    unit: 16,
    english: "to stand out",
    german: "herausstechen, auffallen",
    example: "if companies are very committed to wellbeing",
  },
  {
    unit: 16,
    english: "to deal with",
    german: "umgehen mit, behandeln",
    example: "the immediate effects of employee sickness",
  }
];
