export const questions = [
    // Unit 1
    {
        unit: 1,
        english: "database administrator",
        german: "Datenbankadministrator",
        example: "A database administrator manages and maintains databases to ensure their confidentiality, integrity, and availability."
    },
    {
        unit: 1,
        english: "helpdesk supervisor",
        german: "Helpdeskleitung",
        example: "A helpdesk supervisor manages and oversees a team of helpdesk staff, ensuring efficient resolution of technical issues and maintaining customer service quality."
    },
    {
        unit: 1,
        english: "project manager",
        german: "Projektleiter",
        example: "A project manager plans, organizes, and oversees projects to ensure they are completed on time, within budget, and meet specific goals."
    },
    {
        unit: 1,
        english: "software developer",
        german: "Softwareentwickler",
        example: "A software developer designs, builds, and maintains software applications or systems to meet user needs."
    },
    {
        unit: 1,
        english: "support technician",
        german: "Technischer Supportmitarbeiter",
        example: "A support technician assists and resolves IT issues for users."
    },
    {
        unit: 1,
        english: "systems analyst",
        german: "Systemanalytiker",
        example: "A systems analyst evaluates and designs IT systems to improve efficiency and meet business requirements."
    },
    { unit: 1, english: "to be responsible for", german: "verantwortlich sein für", example: null },
    { unit: 1, english: "to look after computers", german: "sich um Computer kümmern", example: null },
    { unit: 1, english: "to install software", german: "Software installieren", example: null },
    { unit: 1, english: "to diagnose a problem", german: "ein Problem erkennen", example: null },
    { unit: 1, english: "to maintain a database", german: "eine Datenbank instand halten, aktualisieren, pflegen", example: null },
    { unit: 1, english: "normally", german: "normalerweise, in der Regel", example: null },
    { unit: 1, english: "generally", german: "im Allgemeinen", example: null },
    { unit: 1, english: "hardly ever", german: "fast nie, kaum", example: null },
    { unit: 1, english: "occasionally", german: "gelegentlich", example: null },
    { unit: 1, english: "usually", german: "meistens, nomralerweise", example: null },
    { unit: 1, english: "duty, duties", german: "Aufgabe(n), Pflicht(en)", example: null },
    { unit: 1, english: "supplier", german: "Zulieferer, Lieferant, Ausrüster", example: null },
    { unit: 1, english: "provider", german: "Anbieter", example: null },
    { unit: 1, english: "production facility", german: "Produktionsstätte", example: null },
    { unit: 1, english: "customer", german: "Kunde, Verbraucher", example: null },
    { unit: 1, english: "client", german: "Kunde, Klient", example: null },
    { unit: 1, english: "consumer", german: "Verbraucher, Abnehmer, Käufer", example: null },
    { unit: 1, english: "minutes", german: "Protokoll", example: null },
    { unit: 1, english: "supply", german: "Angebot, Vorrat", example: null },
    { unit: 1, english: "to supply", german: "beliefern, liefern", example: null },
    { unit: 1, english: "application", german: "Anwendung, Bewerbung", example: null },
    { unit: 1, english: "available", german: "verfügbar", example: null },
    { unit: 1, english: "to launch", german: "neu auf den Markt bringen", example: null },
    { unit: 1, english: "field", german: "Feld, Bereich, Gebiet", example: null },
    { unit: 1, english: "industry", german: "Branche, Gewerbe", example: null },
    { unit: 1, english: "in charge of", german: "mit der Leitung betraut, verantwortlich für", example: null },
    { unit: 1, english: "character(s)", german: "Zeichen, Eigenschaft", example: null },
    { unit: 1, english: "colleague(s)", german: "Kollegin, Kollegen", example: null },
    { unit: 1, english: "among colleagues", german: "unter Kollegen", example: null },
    { unit: 1, english: "to remind someone of something", german: "jemanden an etwas erinnern", example: null },
    { unit: 1, english: "to work from home", german: "Homeoffice machen, von zu Hause aus arbeiten", example: null },

    // Unit 2
    { unit: 2, english: "folder", german: "Ordner, Mappe", example: null },
    { unit: 2, english: "filename", german: "Dateiname", example: null },
    { unit: 2, english: "double click", german: "Doppelklick", example: null },
    { unit: 2, english: "to drag", german: "ziehen", example: null },
    { unit: 2, english: "to select", german: "wählen, auswählen", example: null },
    { unit: 2, english: "to choose", german: "aussuchen, auswählen", example: null },
    { unit: 2, english: "item", german: "Objekt, Gegenstand", example: null },
    { unit: 2, english: "to plug into", german: "verbinden, einstecken", example: null },
    { unit: 2, english: "to insert", german: "einsetzen, einfügen", example: null },
    { unit: 2, english: "power socket", german: "Steckdose, Stromanschluss", example: null },
    { unit: 2, english: "to switch off", german: "ausschalten", example: null },
    { unit: 2, english: "to disconnect", german: "trennen, unterbrechen", example: null },
    { unit: 2, english: "vendor", german: "Lieferant, Verkäufer", example: null },
    { unit: 2, english: "proprietary software", german: "proprietäre Software", example: null },
    { unit: 2, english: "to take part in", german: "mitmachen", example: null },

    // Unit 3
    { unit: 3, english: "dash", german: "Bindestrich, Strich", example: null },
    { unit: 3, english: "underscore", german: "Unterstrich", example: null },
    { unit: 3, english: "slash", german: "Schrägstrich", example: null },
    { unit: 3, english: "question mark", german: "Fragezeichen", example: null },
    { unit: 3, english: "to pick up", german: "aufheben, auswählen, abholen", example: null },
    { unit: 3, english: "calculator", german: "Rechner", example: null },
    { unit: 3, english: "torch", german: "Taschenlampe, Fackel", example: null },
    { unit: 3, english: "customise", german: "individuell einrichten", example: null },
    { unit: 3, english: "subject line", german: "Betreffzeile", example: null },
    { unit: 3, english: "recipient’s address", german: "Empfängeradresse", example: null },
    { unit: 3, english: "attachment button", german: "Knopf für den Anhang", example: null },
    { unit: 3, english: "spell checker", german: "Rechtschreibprüfung", example: null },
    { unit: 3, english: "blind carbon copy (BCC)", german: "Blindkopie", example: null },
    { unit: 3, english: "reply button", german: "Antwortknopf", example: null },
    { unit: 3, english: "to interrupt", german: "unterbrechen", example: null },

    // Unit 4
    { unit: 4, english: "inquiry, enquiry", german: "Anfrage", example: null },
    { unit: 4, english: "to improve", german: "verbessern, steigern, erhöhen", example: null },
    { unit: 4, english: "to divide by", german: "dividieren, teilen durch", example: null },
    { unit: 4, english: "to subtract from", german: "abziehen von, subtrahieren", example: null },
    { unit: 4, english: "to multiply by", german: "multiplizieren", example: null },
    { unit: 4, english: "equals", german: "ist gleich, gleich", example: null },
    { unit: 4, english: "bracket", german: "Klammer", example: null },
    { unit: 4, english: "misspell", german: "falsch schreiben", example: null },
    { unit: 4, english: "to retrieve a record", german: "Einen Datensatz abrufen", example: null },
    { unit: 4, english: "unique", german: "einzigartig", example: null },
    { unit: 4, english: "to enter data", german: "Daten eingeben, einpflegen", example: null },
    { unit: 4, english: "to run a report", german: "Einen Bericht abrufen", example: null },
    { unit: 4, english: "to deploy software", german: "Software einsetzen, installieren, bereitstellen", example: null },
    { unit: 4, english: "to look after the network", german: "sich um das Netzwerk kümmern", example: null },
    { unit: 4, english: "to set up an account", german: "Ein Konto einrichten", example: null },
    { unit: 4, english: "to work on the helpdesk", german: "am Helpdesk arbeiten", example: null },
    { unit: 4, english: "to set permissions", german: "Berechtigungen setzen", example: null },
    { unit: 4, english: "to check logs", german: "Protokolle kontrollieren, überprüfen", example: null },
    { unit: 4, english: "to reset a password", german: "Passwort zurücksetzen", example: null },
    { unit: 4, english: "to access a desktop", german: "Auf einen Desktop zugreifen", example: null },
    { unit: 4, english: "dedicated server", german: "dedizierter Server", example: null },

    // Unit 5
    { unit: 5, english: "suitable", german: "passend, geeignet", example: null },
    { unit: 5, english: "purchase", german: "Kauf, Einkauf", example: null },
    { unit: 5, english: "to purchase", german: "einkaufen, erwerben", example: null },
    { unit: 5, english: "spare", german: "übrig", example: null },
    { unit: 5, english: "warranty", german: "Garantie", example: null },
    { unit: 5, english: "extended", german: "erweitert", example: null },
    { unit: 5, english: "freemium pricing", german: "Basisservice gratis, erweiterter Service kostet", example: null },
    { unit: 5, english: "subscription pricing", german: "Service im Abonnement", example: null },
    { unit: 5, english: "to recommend", german: "empfehlen", example: null },
    { unit: 5, english: "opinion", german: "Meinung", example: null },
    { unit: 5, english: "small and medium sized-enterprise (SME)", german: "kleines / mittelständiges Unternehmen", example: null },
    { unit: 5, english: "in conclusion", german: "zum Schluss, schließlich", example: null },
    { unit: 5, english: "to sum up", german: "zusammenfassen", example: null },

    // Unit 6
    { unit: 6, english: "work environment", german: "Arbeitsumgebung", example: null },
    { unit: 6, english: "privacy", german: "Privatsphäre", example: null },
    { unit: 6, english: "to feature", german: "bieten, herausstellen", example: null },
    { unit: 6, english: "feature", german: "Merkmal", example: null },
    { unit: 6, english: "voice recognition", german: "Stimmerkennung", example: null },
    { unit: 6, english: "video conferencing", german: "Videokonferenz", example: null },
    { unit: 6, english: "face-to-face", german: "persönlich, von Angesicht zu Angesicht", example: null },
    { unit: 6, english: "participant", german: "Teilnehmer", example: null },
    { unit: 6, english: "advantage", german: "Vorteil", example: null },
    { unit: 6, english: "disadvantage", german: "Nachteil", example: null },
    { unit: 6, english: "B2B business to business", german: "Unternehmen-zu-Unternehmen, Großhandel", example: null },
    { unit: 6, english: "B2C business to consumer", german: "Unternehmen-zu-Verbraucher, Einzelhandel", example: null },
    { unit: 6, english: "brick and click", german: "online und vor Ort", example: null },
    { unit: 6, english: "brick and mortar", german: "(nur) vor Ort", example: null },
    { unit: 6, english: "digital rights management (DRM)", german: "Digitale Rechteverwaltung, Kopierschutz", example: null },
    { unit: 6, english: "near field communication (NFC)", german: "Nahfeldkommunikation", example: null },
    { unit: 6, english: "collaboration", german: "Zusammenarbeit, Mitarbeit", example: null },
    { unit: 6, english: "to collaborate", german: "zusammenarbeiten, mitarbeiten", example: null },
    { unit: 6, english: "location", german: "Ort, Standort", example: null },

    // Unit 7
    { unit: 7, english: "analysis", german: "Analyse, Untersuchung", example: null },
    { unit: 7, english: "to analyse", german: "analysieren, untersuchen", example: null },
    { unit: 7, english: "to approve", german: "zustimmen, genehmigen", example: null },
    { unit: 7, english: "approval", german: "Zustimmung, Genehmigung", example: null },
    { unit: 7, english: "specification", german: "Spezifikation", example: null },
    { unit: 7, english: "to access", german: "zugreifen", example: null },
    { unit: 7, english: "access", german: "Zugang, Zugriff", example: null },
    { unit: 7, english: "accessible", german: "zugänglich", example: null },
    { unit: 7, english: "to require", german: "erfordern, benötigen", example: null },
    { unit: 7, english: "requirement", german: "Anforderung, Voraussetzung", example: null },
    { unit: 7, english: "milestone", german: "Meilenstein", example: null },
    { unit: 7, english: "release", german: "Veröffentlichung", example: null },
    { unit: 7, english: "schedule", german: "Plan", example: null },
    { unit: 7, english: "rough(ly)", german: "ungefähr, grob geschätzt", example: null },

    // Unit 8
    { unit: 8, english: "failure", german: "Fehler, Ausfall, Versagen", example: null },
    { unit: 8, english: "fault", german: "Fehler, Störung", example: null },
    { unit: 8, english: "faulty", german: "fehlerhaft", example: null },
    { unit: 8, english: "to receive", german: "erhalten, bekommen", example: null },
    { unit: 8, english: "to diagnose", german: "feststellen, prüfen", example: null },
    { unit: 8, english: "diagnosis", german: "Diagnose", example: null },
    { unit: 8, english: "troubleshooting", german: "Fehlerbehebung", example: null },
    { unit: 8, english: "to escalate", german: "eskalieren", example: null }
];